#include <CrcLib.h>

#ifndef PIN_MAPPINGS_H
#define PIN_MAPPINGS_H

/**
 * Connexions des moteurs omnidirectionnels
 */
#define FRONT_RIGHT_DRIVE_PIN CRC_PWM_3
#define BACK_RIGHT_DRIVE_PIN CRC_PWM_2
#define BACK_LEFT_DRIVE_PIN CRC_PWM_1
#define FRONT_LEFT_DRIVE_PIN CRC_PWM_4

#define FRONT_LEFT_MULTIPLIER 1.8
#define MAXIMUM_MOVEMENT_SPEED 90

/**
 * Connexions du piquet
 */
#define PIQUET_ROTATOR_SERVO_PIN CRC_PWM_11
#define PIQUET_STOPPER_SERVO_PIN CRC_PWM_12

#define PIQUET_IDLE_TARGET_ROTATION 0
#define PIQUET_RELOADING_TARGET_ROTATION 140
#define PIQUET_SPEED 15
#define PIQUET_MANUAL_ROTATOR_DELAY 1000
#define PIQUET_MANUAL_STOPPER_DELAY 500
#define PIQUET_STOPPER_CLOSING_OFFSET 20

/**
 * Connexions de la pince
 */
#define PINCE_VERTICAL_DRIVE_PIN CRC_PWM_5
#define PINCE_HORIZONTAL_DRIVE_PIN CRC_PWM_6
#define PINCE_DOIGT_SERVO_1_PIN CRC_PWM_7
#define PINCE_DOIGT_SERVO_2_PIN CRC_PWM_8
#define PINCE_POIGNET_SERVO_PIN CRC_PWM_9
#define PINCE_FLIP_SERVO_PIN CRC_PWM_10

#define PINCE_UPPER_LIMIT_SWITCH_PIN CRC_DIG_1
#define PINCE_LOWER_LIMIT_SWITCH_PIN CRC_DIG_2
#define PINCE_LEFT_LIMIT_SWITCH_PIN CRC_DIG_9
#define PINCE_RIGHT_LIMIT_SWITCH_PIN CRC_DIG_10
#define PINCE_VERTICAL_RELOAD_LIMIT_SWITCH_PIN CRC_DIG_11
#define PINCE_HORIZONTAL_RELOAD_LIMIT_SWITCH_PIN CRC_DIG_12

#define PINCE_FLIP_MIN_ANGLE 0
#define PINCE_FLIP_IDLE_ANGLE 80
#define PINCE_FLIP_MAX_ANGLE 180
#define PINCE_FLIP_MANUAL_DELAY 1000
#define PINCE_FLIP_SPEED 40
#define PINCE_FLIP_DROP_DELAY 5000

#define PINCE_DOIGT_IDLE_ANGLE 45
#define PINCE_DOIGT_MAX_ANGLE 180

constexpr int16_t PINCE_POIGNET_MIN_ANGLE = 0;
constexpr int16_t PINCE_POIGNET_IDLE_ANGLE = 90;
constexpr int16_t PINCE_POIGNET_MAX_ANGLE = 180;
constexpr int16_t PINCE_POIGNET_DEBOUNCE_TIME = 250;

/**
 * Connexions du propulseur
 */
#define PROPULSEUR_MOTOR_PIN CRC_DIG_7

/**
 * Mappings de la manette
 */
constexpr BUTTON CONTROLLER_PINCE_UP_MOVEMENT = BUTTON::ARROW_UP;
constexpr BUTTON CONTROLLER_PINCE_DOWN_MOVEMENT = BUTTON::ARROW_DOWN;
constexpr BUTTON CONTROLLER_PINCE_LEFT_MOVEMENT = BUTTON::ARROW_LEFT;
constexpr BUTTON CONTROLLER_PINCE_RIGHT_MOVEMENT = BUTTON::ARROW_RIGHT;
constexpr ANALOG CONTROLLER_PINCE_POIGNET_LEFT = ANALOG::GACHETTE_L;
constexpr ANALOG CONTROLLER_PINCE_POIGNET_RIGHT = ANALOG::GACHETTE_R;
constexpr BUTTON CONTROLLER_PINCE_MANUAL_FLIP = BUTTON::START;
constexpr BUTTON CONTROLLER_PINCE_DOIGTS = BUTTON::L1;
constexpr BUTTON CONTROLLER_PIQUET_TOGGLE_ROTATOR = BUTTON::COLORS_UP;
constexpr BUTTON CONTROLLER_PIQUET_TOGGLE_STOPPER = BUTTON::COLORS_RIGHT;

constexpr BUTTON SHOOT_KEY = BUTTON::R1;
constexpr BUTTON RELOAD_KEY = BUTTON::COLORS_LEFT;


#endif